### ISSUE TITLE
Not able to use in latest Orbiter (after d3d9 merge)

### ISSUE THREAD

**Issue by supersonic71** [Piraxus/OrbiterSkyboltClient#14]
I get this error when I change to Skybolt in Video tab : 
![image](https://user-images.githubusercontent.com/17806210/188465868-8f15f071-60aa-4cb2-bed8-16e320c80609.png)

Orbiter used : https://github.com/orbitersim/orbiter/actions/runs/2990259285
Skybolt Client version : 1.0.3 

I believe this issue occurred after d3d9 was merged into Orbiter : https://github.com/orbitersim/orbiter/pull/146 
Edit : not sure if this is skybolt-client issue or orbiter issue, should I post there instead?

**Comment by matthew-reid** [comment]
Thanks for the report. I tested it and found the same issue. It looks like there were some changes to the orbiter SDK interface which are not binary compatible with the skybolt client. I will update the client to compile against the new interface.

**Comment by supersonic71** [comment]
Thank you! :)
