### ISSUE TITLE
Visual glitch when drawing exhaust particles while in bodies that are not earth

### ISSUE THREAD

**Issue by OvalDreamX** [Piraxus/OrbiterSkyboltClient#5]
![image](https://user-images.githubusercontent.com/71135484/183698238-0098ec13-d1e6-4eb8-b602-62f37bdcb483.png)

And here on Europa
![image](https://user-images.githubusercontent.com/71135484/183698563-96b60bc2-34f5-4c03-894b-e2266879db75.png)

It does the same whether on planets with atmosphere or not as long as theyre nor Earth

**Comment by matthew-reid** [comment]
Thanks for the report. I've identified the cause. It will be fixed in the next release.

**Comment by matthew-reid** [comment]
Fixed in v1.0.3
