### ISSUE TITLE
Taking off from mars glitches the physics system

### ISSUE THREAD

**Issue by OvalDreamX** [Piraxus/OrbiterSkyboltClient#8]
When trying to take off from the ground there, the craft either shakes or just teleports after some seconds of normal functioning. I still havent been able to determine what causes it to either teleport or shake.

Update 1: it seems that the shuttle a teleports, while the dg shakes most of the time
Update 2; the "shaking" appears to be only a visual shake around the ground nearest to the ship

**Comment by matthew-reid** [comment]
I suspect this is a physics instability bug in Orbiter, not an issue with the Skybolt client. I tried the d3d9 client and got the same result. A few seconds after takeoff from Olympus the Shuttle A either teleports into space or starts jumping around randomly near the ground.

**Comment by n7275** [comment]
Same issue here. I was testing my tesseral gravity branch and thought I had a bug, but it appears in the latest master branch as well.

**Comment by matthew-reid** [comment]
@n7275 are you able to confirm whether the issue is still present when not using the skybolt client?

**Comment by n7275** [comment]
That's correct. This was with the D3D9 client and is likely unrelated to graphics. The issue also presents itself in places other than just Mars, although more testing is needed to determine if if Mars is just a coincidence that we notice it there. Randomly warping off into oblivion or phantom aparent aceleration also happen near the Earth and Moon, but not regularly or reliably.

**Comment by matthew-reid** [comment]
@n7275 thanks for the info. Has this issue been raised yet on the orbiter repo / forum?

**Comment by n7275** [comment]
To my knowledge, no.

Let's make sure that when we do we state that Mars, in the default scenerios (it could be MJD related), is the best place to observe it but it is likely a more fundamental issue.
